import express from "express";
const app = express();


app.get("/", (req, res) => {
    res.send("Bom Dia meu amigo");

});

app.get("/sobre", (req, res) => {
    res.send("Minha pagina sobre");
});

app.get("/blog", (req, res) => {
    res.send("Bem-vindo ao meu blog");
});

app.get("/ola/:cargo/:nome", (req, res) => {
    res.send("<h1>" + req.params.nome + "</h1>");
    res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
});

app.listen(8082, () => {
    console.log("Rodando");
});
