import express from "express";
const app = express();

import { fileURLToPath } from "url";
import { dirname } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

app.get("/", (req, res) => {
    res.sendFile(__dirname + "/index.html");

});

app.get("/sobre", (req, res) => {
    res.send("Minha pagina sobre");
});

app.get("/blog", (req, res) => {
    res.send("Bem-vindo ao meu blog");
});

app.get("/ola/:cargo/:nome", (req, res) => {
    res.send(`<h1>${req.params.nome}</h1> + <br + <h2>Seu cargo: ${req.params.cargo}</h2>`);
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
    // res.send("<h2> seu cargo :" + req.params.cargo + "</h2>")
});

app.listen(8082, () => {
    console.log("Rodando");
});
